### ISSUE TITLE
Описать все таблицы связанные с поездами и их вагонами

### ISSUE THREAD

**Issue by PtpJam** [PtpJam/train_ticket_manager#1]
- Рейс
- Поезд
- Вагон
- Тип_вагона
- Инвентарь 
- Персонал
- Тип_Персонала 
- Личные_данные

**Comment by Xepobopa** [comment]
[script.sql.zip](https://github.com/PtpJam/train_ticket_manager/files/8747723/script.sql.zip)

**Comment by daniilvinn** [comment]
[script.zip](https://github.com/PtpJam/train_ticket_manager/files/8837582/script.zip)
Script update
