### ISSUE TITLE
Реализовать отдельно dll для клиента и администратора

### ISSUE THREAD

**Issue by PtpJam** [PtpJam/train_ticket_manager#8]
В dll клиента предоставить обвёртки для возможности просмотра поездов и их расписания
В dll менеджера реализовать возможности клиента + логику "покупки клиента"

Инфа ниже
https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio?pivots=dotnet-6-0

**Comment by Xepobopa** [comment]
@PtpJam Пока что делать в консоли, потом на парах перенесём в Windows Forms?
